# Default values

api:
  name: testtaskps-api
  service: testtaskps-api-service
  replicas: 1
  image: mafmax/testtaskps-api:1.2.4
  port: 80 # Port on POD.
  servicePort: 8888
db:
  service: mongodb-filesstore-service
  name: mongodb-filesstore
  image: mongo
  port: 27017
  servicePort: 7777
background:
  name: testtaskps-background-worker
  image: mafmax/testtaskps-background-worker:1.0.0
  port: 80 
client:
  name: testtaskps-client
  service: testtaskps-client-service
  servicePort: 6666
  image: mafmax/testtaskps-client:1.1.11
  port: 3000